## YAML Template.
## YAML Template.
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
    

spring:
  application:
    name: externalapi

#logging:
#  level:
#    com.example.howtodoinjava: DEBUG
