eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:  http://192.168.30.58:8761/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5

spring:
  application:
    name: external-api
